# Generated by Django 5.1.1 on 2024-10-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodData",
            fields=[
                ("SerialNo", models.IntegerField(primary_key=True, serialize=False)),
                ("Title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Instructions",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                ("Image_Name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "Cleaned_Ingredients",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
            options={
                "db_table": "FoodData",
            },
        ),
    ]
