# Generated by Django 5.1.1 on 2024-10-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fooddata",
            options={"managed": False},
        ),
    ]
