# Generated by Django 5.1.1 on 2024-10-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_fooddata_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fooddata",
            options={},
        ),
    ]
